---
name: Test Ansible roles with Molecule
description: Run Molecule to test Ansible roles
author: Sean Nelson <hyperkineticnerd@gmail.com>

inputs:
  registry:
    description: The Registry where the image can be found. Defaults to ``.
    required: false
    default: ghcr.io
  namespace:
    description: The [Docker Hub](https://hub.docker.com/) namespace where the image can be found. Defaults to `hyperkineticnerd`.
    required: false
    default: hyperkineticnerd
  image:
    description: The image you want to run on. Defaults to `ubi`.
    required: false
    default: github-action-molecule
  tag:
    description: The tag of the container image to use. Defaults to `latest`.
    required: false
    default: latest
  options:
    description: Options you can pass to [`tox`](https://tox.readthedocs.io/en/latest/), for example `--parallel all`.
    required: false
  command:
    description: What command to pass to [molecule](https://molecule.readthedocs.io/en/latest/), for example `lint` or `syntax`. Defaults to `test`.
    required: false
    default: test
  scenario:
    description: The molecule scenario to run. Default to `default`.
    required: false
    default: default

runs:
  using: docker
  image: docker://${{ inputs.registry }}/${{ inputs.namespace }}/${{ inputs.image }}:${{ inputs.tag }}
  env:
    ANSIBLE_ROLES_PATH: "../"
    ANSIBLE_ASYNC_DIR: "/tmp/.ansible_async"
    namespace: ${{ inputs.namespace }}
    image: ${{ inputs.image }}
    tag: ${{ inputs.tag }}
    options: ${{ inputs.options }}
    command: ${{ inputs.command }}
    scenario: ${{ inputs.scenario }}
#   entrypoint:
#   args:
#     - 

branding:
  icon: play
  color: green
