---
name: Test Ansible roles with Molecule
description: Run Molecule to test Ansible roles
author: Sean Nelson <hyperkineticnerd@gmail.com>

inputs:
  options:
    description: Options you can pass to [`tox`](https://tox.readthedocs.io/en/latest/), for example `--parallel all`.
    required: false
  command:
    description: What command to pass to [molecule](https://molecule.readthedocs.io/en/latest/), for example `lint` or `syntax`. Defaults to `lint`.
    required: false
    default: lint
  scenario:
    description: The molecule scenario to run. Default to `default`.
    required: false
    default: default

runs:
  using: docker
  image: docker://quay.io/ansible/creator-ee:latest
  env:
    ANSIBLE_ROLES_PATH: "../"
    ANSIBLE_ASYNC_DIR: "/tmp/.ansible_async"
    scenario: ${{ inputs.scenario }}
    options: ${{ inputs.options }}
  entrypoint: molecule
  args:
    - ${{ inputs.command }}

branding:
  icon: play
  color: green
